# This workflow will publish a new version of the documentation to the gh-pages branch

name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ github.repository == 'slaclab/Archive-Viewer' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge
          activate-environment: archive-viewer-dev

      - name: Build Docs
        shell: bash -l {0}
        run: |
          mkdocs build
  
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/